### ISSUE TITLE
请问导出图片word要怎么写之后要怎么处理？

### ISSUE THREAD

**Issue by niyizhong123** [kmood/officeexport-java#1]
没看明白如何处理生成的xml和ftl 感谢回复。

**Comment by kmood** [comment]
> 没看明白如何处理生成的xml和ftl 感谢回复。

https://github.com/kmood/officeexport-java/blob/master/src/test/java/com/test/test.java  里面添加图片导出的示例，主要原理是通过在图片格式设置->可选文字中添加占位符即可实现图片导出，占位符格式为{^占位符^}（例 {^title^}），占位图片的格式即输出格式，近期会出详细的文档，感谢反馈。
