### ISSUE TITLE
转义

### ISSUE THREAD

**Issue by wangyuhuich** [kmood/officeexport-java#2]
如何在word里进行对一些字段的转义

**Comment by wangyuhuich** [comment]
表格渲染中，对一个值进行转义

**Comment by kmood** [comment]
模板中包含以上语法对应的字符或者'\'需要进行转义，需要在特殊字符前增加'\'进行转义
例如："{" 转义后 "\{","\" 转义后"\\"

**Comment by kmood** [comment]
模板中包含以上语法对应的字符或者'\'需要进行转义，需要在特殊字符前增加'\'进行转义
例如："{" 转义后 "\{","\" 转义后"\\"

**Comment by kmood** [comment]
模板中包含以上语法对应的字符或者'\\'需要进行转义，需要在特殊字符前增加'\\'进行转义
例如："{" 转义后 "\\{","\\" 转义后"\\\\"

**Comment by kmood** [comment]
模板中包含语法中对应的字符或者'\\'时需要进行转义，需要在特殊字符前增加'\\'进行转义
例如："{" 转义后 "\\{","\\" 转义后"\\\\"
