### ISSUE TITLE
WordModelParser.Compile报空指针错误

### ISSUE THREAD

**Issue by Worliaro** [kmood/officeexport-java#6]
![image](https://user-images.githubusercontent.com/30817134/100178325-a0dfc800-2f0e-11eb-9db0-e90fce963b45.png)
![image](https://user-images.githubusercontent.com/30817134/100178426-ccfb4900-2f0e-11eb-8270-b7d5682beaec.png)
大佬，我在使用时，这块老是报空指针是咋回事呢？应该如何修改

**Comment by kmood** [comment]
使用的测试用例吗

**Comment by kmood** [comment]
单元测试暂时没做维护，图片导出可以参考：https://github.com/kmood/officeexport-java/blob/master/src/main/java/main/Main.java  中  testPictureOutModel

**Comment by Worliaro** [comment]
感谢大佬
但不知为何我导出的doc是这样子的呢
![image](https://user-images.githubusercontent.com/30817134/100529981-8ddb3980-3227-11eb-9fb0-73eed1807eb0.png)
下面图片是我原始的xml文件， 我另存为的xml文件里没有   alt="{^pic^}"  。 alt="{^pic^}"是我仿照你的项目里的 picture.xml文件里新加的，但是最后生成的doc文件里就报图片缺失了呢？
![image](https://user-images.githubusercontent.com/30817134/100529992-b105e900-3227-11eb-8c29-e24d2dcfdf73.png)

**Comment by kmood** [comment]
使用的那个版本的，方便的话把关键部分代码，以及模板截图一下

**Comment by kmood** [comment]
> 感谢大佬
> 但不知为何我导出的doc是这样子的呢
> ![image](https://user-images.githubusercontent.com/30817134/100529981-8ddb3980-3227-11eb-9fb0-73eed1807eb0.png)
> 下面图片是我原始的xml文件， 我另存为的xml文件里没有 alt="{^pic^}" 。 alt="{^pic^}"是我仿照你的项目里的 picture.xml文件里新加的，但是最后生成的doc文件里就报图片缺失了呢？
> ![image](https://user-images.githubusercontent.com/30817134/100529992-b105e900-3227-11eb-8c29-e24d2dcfdf73.png)

使用的那个版本的，方便的话把关键部分代码，以及模板截图一下

**Comment by Worliaro** [comment]
感谢大佬   我好像发现问题了  正在排查
我这里从前端获得到的是未加密的base64编码，为了方便，没有把编码转换为图片保存，而是直接存成了txt文件，然后获取的时候直接读取txt文件的内容即为未加密的base64编码，如下
![image](https://user-images.githubusercontent.com/30817134/100530803-9173be00-3231-11eb-901e-51ed130e9c09.png)
对比你的项目中测试Demo，发现代码里传的是对 base64编码进行了加密的

**Comment by kmood** [comment]
> 感谢大佬 我好像发现问题了 正在排查
> 我这里从前端获得到的是未加密的base64编码，为了方便，没有把编码转换为图片保存，而是直接存成了txt文件，然后获取的时候直接读取txt文件的内容即为未加密的base64编码，如下
> ![image](https://user-images.githubusercontent.com/30817134/100530803-9173be00-3231-11eb-901e-51ed130e9c09.png)
> 对比你的项目中测试Demo，发现代码里传的是对 base64编码进行了加密的

好的 wiki里面有关图片占位符的说明，参考下面的地址https://github.com/kmood/officeexport-java/wiki/%E6%A8%A1%E6%9D%BF%E5%BC%80%E5%8F%91

**Comment by Worliaro** [comment]
> > 感谢大佬 我好像发现问题了 正在排查
> > 我这里从前端获得到的是未加密的base64编码，为了方便，没有把编码转换为图片保存，而是直接存成了txt文件，然后获取的时候直接读取txt文件的内容即为未加密的base64编码，如下
> > ![image](https://user-images.githubusercontent.com/30817134/100530803-9173be00-3231-11eb-901e-51ed130e9c09.png)
> > 对比你的项目中测试Demo，发现代码里传的是对 base64编码进行了加密的
> 
> 好的 wiki里面有关图片占位符的说明，参考下面的地址https://github.com/kmood/officeexport-java/wiki/%E6%A8%A1%E6%9D%BF%E5%BC%80%E5%8F%91

好的  感谢

**Comment by Worliaro** [comment]
![image](https://user-images.githubusercontent.com/30817134/100547550-46de5a00-32a2-11eb-899d-5bb9a39d061e.png)
![image](https://user-images.githubusercontent.com/30817134/100547575-7d1bd980-32a2-11eb-9885-2fbd87ec3816.png)
bao报符号错误是怎么回事呢?  能确认的是  我使用的是  半角英文的{^pic^}

**Comment by kmood** [comment]
> ![image](https://user-images.githubusercontent.com/30817134/100547550-46de5a00-32a2-11eb-899d-5bb9a39d061e.png)
> ![image](https://user-images.githubusercontent.com/30817134/100547575-7d1bd980-32a2-11eb-9885-2fbd87ec3816.png)
> bao报符号错误是怎么回事呢? 能确认的是 我使用的是 半角英文的{^pic^}

一般是由于模板的原因导致的，可以提供下模板，以及关键部分代码

**Comment by Worliaro** [comment]
> > ![image](https://user-images.githubusercontent.com/30817134/100547550-46de5a00-32a2-11eb-899d-5bb9a39d061e.png)
> > ![image](https://user-images.githubusercontent.com/30817134/100547575-7d1bd980-32a2-11eb-9885-2fbd87ec3816.png)
> > bao报符号错误是怎么回事呢? 能确认的是 我使用的是 半角英文的{^pic^}
> 
> 一般是由于模板的原因导致的，可以提供下模板，以及关键部分代码

谢谢大佬，已解决，我最后将你Demo里的 alt="{^pic^}" 贴进去就可以了
