### ISSUE TITLE
if  else 判断

### ISSUE THREAD

**Issue by yeliqiu** [kmood/officeexport-java#9]
请问这个导出模板中可以写 if  else 相关的判断语句吗？

**Comment by kmood** [comment]
> 请问这个导出模板中可以写 if else 相关的判断语句吗？

最近正在考虑加上if else判断了，我这边也用到了

**Comment by kmood** [comment]
不打算在支持if else,主要原因为此类逻辑判断应放在代码层面组织数据实现，模板配置不宜过于复杂
